---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment
  labels:
    app: helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
       app: helloworld
    spec:
      containers:
      - name: helloworld
        image: partha14/helloworld:v1
        ports:
        - containerPort: 80
